name: mayphus.org

on:
  push:
    branches: [main]
  workflow_dispatch:
  repository_dispatch:
    types: [notes-update]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout mayphus/org
        uses: actions/checkout@v4
        with:
          repository: mayphus/org
          token: ${{ secrets.TOKEN }}
          path: org

      - name: Prepare content
        run: |
          mkdir -p content
          mv org/*.org content/
          rm -fr org
          rm -fr content/README.org
          
      - name: Setup
        uses: actions/setup-node@v4
        with:
          cache: 'npm'

      - name: Build
        run: |
          npm install
          npm run astro check
          npm run build

      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          wranglerVersion: 4.19.1