name: mayphus-org

on:
  push:
    branches:
      - main
      - 'codex*'
      - 'feature*'
  workflow_dispatch:
  repository_dispatch:
    types: [notes-update]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Checkout mayphus/notes
        uses: actions/checkout@v4
        with:
          repository: mayphus/notes
          token: ${{ secrets.TOKEN }}
          path: notes

      - name: Prepare content
        run: |
          mkdir -p content
          mv notes/*.org content/
          rm -fr notes
          rm -fr content/README.org
          
      - name: Setup
        uses: actions/setup-node@v4
        with:
          cache: 'npm'

      - name: Build
        run: |
          npm install
          npm run astro check
          npm run build

      - name: Deploy preview
        if: startsWith(github.ref, 'refs/heads/codex') || startsWith(github.ref, 'refs/heads/feature')
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          wranglerVersion: 4.19.1
          command: deploy --env preview
          environment: preview

      - name: Deploy production
        if: github.ref == 'refs/heads/main' || github.event_name == 'repository_dispatch'
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          wranglerVersion: 4.19.1
          environment: production
